<?php
require_once __DIR__ . '/../config/database.php';
$ownerUsername='matthaevs';$ownerPassword='matthaevs0203';
$stmt=$pdo->prepare('SELECT id FROM users WHERE username=? LIMIT 1');$stmt->execute([$ownerUsername]);$u=$stmt->fetch();if(!$u)die("Owner account not found. Run install.php first.\n");$uid=(int)$u['id'];
$pdo->prepare('UPDATE users SET password_hash=?,display_name=?,is_owner=1 WHERE id=?')->execute([password_hash($ownerPassword,PASSWORD_DEFAULT),'MANECLANG',$uid]);
$content=['home'=>['welcome'=>'WELCOME','headline'=>'BUILD.\nCREATE.\nEXPLORE.','subtitle'=>'DIGITAL PROJECTS • INTERACTIVE EXPERIENCES • IDEAS','description'=>'A personal collection of projects, experiments, games, and ideas brought to life through technology and creativity.','primaryButton'=>'EXPLORE MY WORK','secondaryButton'=>'GET IN TOUCH','labelNumber'=>'01','labelText'=>'CREATIVE / DIGITAL'],'about'=>['welcome'=>'WHO I AM','headlineTop'=>'ABOUT','headlineBottom'=>'ME.','subtitle'=>'COMPUTER ENGINEERING • TECHNOLOGY • CREATIVE PROJECTS','paragraph1'=>'I am Matthaevs Satzchell L. Maneclang, a Computer Engineering student with a strong interest in technology, programming, and digital creation.','paragraph2'=>'I enjoy learning through building. Whether developing websites, interactive applications, games, or exploring engineering concepts, I see every project as an opportunity to learn, experiment, and improve.','paragraph3'=>'This website is a growing collection of my work, ideas, achievements, and projects as I continue developing my skills and exploring what I can create with technology.','pageNumber'=>'02','pageLabel'=>'ABOUT / PROFILE','profileNumber'=>'01','profileLabel'=>'PERSONAL PROFILE'],'hero'=>['design'=>'sphere']];
$profile=[['id'=>'maneclang','name'=>'MANECLANG','description'=>'Maneclang Website','url'=>'index.html','image'=>'profile.jpg','isNew'=>false,'setupComplete'=>true,'accountUsername'=>$ownerUsername,'protected'=>true]];
$projects=[['id'=>'color-game','title'=>'COLOR GAME','category'=>'GAME','categoryType'=>'GAME','type'=>'GAME / JAVASCRIPT','description'=>'Interactive color recognition game built as a coding activity.','link'=>'uploads/projects/1/color-game/index.html'],['id'=>'web-projects','title'=>'1ST YEAR FINALS','category'=>'WEB','categoryType'=>'WEB','type'=>'HTML / CSS','description'=>'A first-year web requirement developed as a complete website project.','link'=>'uploads/projects/1/web-projects/index.html'],['id'=>'valentine-surprise','title'=>'VALENTINE SURPRISE','category'=>'SOFTWARE','categoryType'=>'SOFTWARE','type'=>'SOFTWARE / APPLICATION','description'=>'A personal interactive website project.','link'=>'uploads/projects/1/valentine-surprise/index.html']];
$featured=[['id'=>'color-game','category'=>'GAME / JAVASCRIPT','type'=>'GAME','title'=>'COLOR GAME','description'=>'An interactive color recognition game designed to test speed, focus, and visual perception.','link'=>'uploads/projects/1/color-game/index.html']];
$achievements=[['id'=>'achievement-original-post','year'=>'SENIOR HIGH SCHOOL','title'=>'BEST IN APPLICATION SYSTEM & BEST IN GAME APPLICATION','description'=>'Recognized for excellence in application and game development during my senior high school years. The achievement demonstrated creativity, technical skills, functionality, practical problem-solving, and the ability to develop working digital applications.\n\nEVALUATION PANEL:\nMr. Ced Falconite — Panelist\nMr. Erickson Catajan — Panelist\nSir Joven Bastasa — ICT Adviser','image'=>'','createdAt'=>'2026-01-01T00:00:00.000Z']];
$skills=[['id'=>'skill-html','title'=>'HTML','description'=>'Building and structuring websites.'],['id'=>'skill-css','title'=>'CSS','description'=>'Creating responsive and modern interfaces.'],['id'=>'skill-javascript','title'=>'JAVASCRIPT','description'=>'Adding interaction and functionality.'],['id'=>'skill-engineering','title'=>'ENGINEERING','description'=>'Exploring technology through practical projects and problem-solving.']];
$items=['maneclangWebsiteProfiles'=>json_encode($profile,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'maneclangWebsiteContent'=>json_encode(['maneclang'=>$content],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'maneclangFeaturedProjects'=>json_encode($featured,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'maneclangProjects'=>json_encode($projects,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'maneclangAchievements_'.$ownerUsername=>json_encode($achievements,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'maneclangGallery_'.$ownerUsername=>'[]','maneclangSkills_'.$ownerUsername=>json_encode($skills,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)];
$stmt=$pdo->prepare('INSERT INTO user_storage(user_id,storage_key,storage_value) VALUES(?,?,?) ON DUPLICATE KEY UPDATE storage_value=VALUES(storage_value)');foreach($items as $k=>$v)$stmt->execute([$uid,$k,$v]);echo "OWNER DATA READY\n";
