<?php
$host='127.0.0.1';$user='root';$pass='';$db='student_portfolio';header('Content-Type:text/plain;charset=utf-8');
try{$pdo=new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$pdo->exec("CREATE TABLE IF NOT EXISTS users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,username VARCHAR(100) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,display_name VARCHAR(150) NOT NULL DEFAULT '',is_owner TINYINT(1) NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB");try{$pdo->exec("ALTER TABLE users ADD COLUMN avatar_path VARCHAR(500) NULL AFTER display_name");}catch(Throwable $e){}
$pdo->exec("CREATE TABLE IF NOT EXISTS user_storage(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL,storage_key VARCHAR(190) NOT NULL,storage_value LONGTEXT NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_user_storage(user_id,storage_key),CONSTRAINT fk_storage_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB");
$un='matthaevs';$pw='matthaevs0203';$s=$pdo->prepare('SELECT id FROM users WHERE username=? LIMIT 1');$s->execute([$un]);$o=$s->fetch();if(!$o){$s=$pdo->prepare('INSERT INTO users(username,password_hash,display_name,is_owner) VALUES(?,?,?,1)');$s->execute([$un,password_hash($pw,PASSWORD_DEFAULT),'MANECLANG']);$oid=(int)$pdo->lastInsertId();}else{$oid=(int)$o['id'];$s=$pdo->prepare('UPDATE users SET password_hash=?,display_name=?,is_owner=1 WHERE id=?');$s->execute([password_hash($pw,PASSWORD_DEFAULT),'MANECLANG',$oid]);}
$defaults=['maneclangWebsiteProfiles'=>json_encode([['id'=>'maneclang','name'=>'MANECLANG','description'=>'Maneclang Website','url'=>'index.html','image'=>'profile.jpg','isNew'=>false,'setupComplete'=>true,'accountUsername'=>$un,'protected'=>true]],JSON_UNESCAPED_UNICODE),'maneclangWebsiteContent'=>'{}','maneclangFeaturedProjects'=>'[]','maneclangProjects'=>'[]','maneclangAchievements_'.$un=>'[]','maneclangGallery_'.$un=>'[]','maneclangSkills_'.$un=>'[]'];$s=$pdo->prepare('INSERT IGNORE INTO user_storage(user_id,storage_key,storage_value) VALUES(?,?,?)');foreach($defaults as $k=>$v)$s->execute([$oid,$k,$v]);
$check=$pdo->prepare("SELECT storage_value FROM user_storage WHERE user_id=? AND storage_key='maneclangProjects' LIMIT 1");$check->execute([$oid]);$pr=$check->fetch();if(!$pr||trim((string)$pr['storage_value'])==='[]'){require __DIR__.'/seed_owner.php';}
echo "UPDATE COMPLETE\n\nOwner login repaired.\nUsername: matthaevs\nPassword: matthaevs0203\nAvatar support: READY\nRegistration: READY\nExisting account data preserved.\n";
}catch(Throwable $e){http_response_code(500);echo "UPDATE FAILED\n\n".$e->getMessage()."\n";}
